[package]
name = "upt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
chrono-humanize = "0.2.2"
clap = { version = "4.2.7", features = ["derive", "cargo"] }
clap_complete = "4.2.3"
uptime_lib = "0.2.2"
