[package]
name = "upt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono-humanize = "0.2.2"
clap = "4.2.7"
clap_complete = "4.2.3"
uptime_lib = "0.2.2"
