[package]
name = "upt"
version = "1.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.30", default-features = false, features = [] }
chrono-humanize = "0.2.3"
clap = { version = "4.4.6", features = ["derive", "cargo"] }
clap_complete = "4.4.4"
crossterm = "0.27.0"
ctrlc = "3.2.5"
home = "0.5.5"
simple-error = "0.3.0"
uptime_lib = "0.2.2"
