name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call: # allow this workflow to be called from other workflows

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # selecting a toolchain either by action or manual `rustup` calls should happen
    # before the plugin, as the cache uses the current rustc version as its cache key
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"

    - name: Build
      run: cargo build --verbose --locked
    - name: Run tests
      run: cargo test --verbose
    - name: Lint
      run: |
        set -exuo pipefail
        cargo fmt --all -- --check
        cargo clippy -- -Dwarnings
    - name: Install tool cargo-deny
      uses: baptiste0928/cargo-install@v2
      with:
        crate: cargo-deny
    - name: Install tool cargo-outdated
      uses: baptiste0928/cargo-install@v2
      with:
        crate: cargo-outdated
    - name: Install tool cargo-pants
      uses: baptiste0928/cargo-install@v2
      with:
        crate: cargo-pants
    - name: Check
      run: |
        set -exuo pipefail
        cargo deny check
        cargo outdated --exit-code 1
        #cargo udeps
        #rm -rf ~/.cargo/advisory-db
        #cargo audit
        cargo pants
