name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # selecting a toolchain either by action or manual `rustup` calls should happen
    # before the plugin, as the cache uses the current rustc version as its cache key
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --verbose --locked
    - name: Run tests
      run: cargo test --verbose
    - name: Lint
      run: |
        cargo fmt --all -- --check
        cargo clippy -- -Dwarnings
    - name: Install cargo check tools
      run: |
        cargo install --locked cargo-deny || true
        cargo install --locked cargo-outdated || true
        #cargo install --locked cargo-udeps || true
        #cargo install --locked cargo-audit || true
        cargo install --locked cargo-pants || true
    - name: Check
      run: |
        cargo deny check
        cargo outdated --exit-code 1
        #cargo udeps
        #rm -rf ~/.cargo/advisory-db
        #cargo audit
        cargo pants